type Parameter = { name?: unknown; in?: unknown; required?: unknown };
type Operation = {
  operationId?: unknown;
  summary?: unknown;
  tags?: unknown;
  parameters?: unknown;
  requestBody?: unknown;
};

const source = process.argv[2] ?? 'https://api.usenotra.com/openapi.json';
const target = new URL('../src/constants/openapi.ts', import.meta.url);
const response = await fetch(source);
if (!response.ok) throw new Error(`Could not fetch ${source}: HTTP ${response.status}`);
const document = (await response.json()) as { paths?: Record<string, Record<string, unknown>> };
const methods = new Set(['get', 'post', 'put', 'patch', 'delete']);
const operations = Object.entries(document.paths ?? {}).flatMap(([path, pathItem]) =>
  Object.entries(pathItem).flatMap(([method, rawOperation]) => {
    if (!methods.has(method) || !isRecord(rawOperation)) return [];
    const operation = rawOperation as Operation;
    if (typeof operation.operationId !== 'string') return [];
    const parameters = Array.isArray(operation.parameters)
      ? operation.parameters.flatMap((rawParameter) => {
          if (!isRecord(rawParameter)) return [];
          const parameter = rawParameter as Parameter;
          if (
            typeof parameter.name !== 'string' ||
            !['path', 'query', 'header'].includes(String(parameter.in))
          ) {
            return [];
          }
          return [{
            name: parameter.name,
            in: parameter.in,
            required: parameter.required === true,
          }];
        })
      : [];
    return [{
      id: operation.operationId,
      method: method.toUpperCase(),
      path,
      summary: typeof operation.summary === 'string' ? operation.summary : operation.operationId,
      tag: Array.isArray(operation.tags) && typeof operation.tags[0] === 'string' ? operation.tags[0] : '',
      parameters,
      hasBody: operation.requestBody !== undefined,
    }];
  }),
).sort((left, right) => left.id.localeCompare(right.id));

const contents = [
  "import type { OpenApiOperation } from '../types/api';",
  '',
  '// Generated by `bun run openapi:sync`; do not edit by hand.',
  `export const OPENAPI_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const satisfies ReadonlyArray<OpenApiOperation>;`,
  '',
].join('\n');

await Bun.write(target, contents);
console.log(`Wrote ${operations.length} operations to ${target.pathname}.`);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
